[Service]
Host = "edgex-ui-go"
Port = 4000
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "static/web"

#Using an default memory db automatically if not configed here.
[Database]
Host = ""
Name = ""
Port = 0
Username = "su"
Password = "su"
  [Database.Scheme]
  User = "user"

[Clients]
    [Clients.CoreData]
    Protocol = 'http'
    Host = 'edgex-core-data'
    Port = 59880
    PathPrefix = "/coredata"

    [Clients.Metadata]
    Protocol = 'http'
    Host = 'edgex-core-metadata'
    Port = 59881
    PathPrefix = "/metadata"

    [Clients.CoreCommand]
    Protocol = 'http'
    Host = 'edgex-core-command'
    Port = 59882
    PathPrefix = "/command"

    [Clients.Notification]
    Protocol = 'http'
    Host = 'edgex-support-notifications'
    Port = 59860
    PathPrefix = "/notification"

    [Clients.Scheduler]
    Protocol = 'http'
    Host = 'edgex-support-scheduler'
    Port = 59861
    PathPrefix = "/scheduler"

    [Clients.RuleEngine]
    Protocol = 'http'
    Host = 'edgex-kuiper'
    Port = 59720
    PathPrefix = "/rule-engine"

    [Clients.System]
    Protocol = 'http'
    Host = 'edgex-sys-mgmt-agent'
    Port = 58890
    PathPrefix = "/system"

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"
ConfigRegistryStem="edgex/appservices/"
ServiceVersion="2.0"