[Writable]
PersistData = true
LogLevel = "INFO"

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
ServerBindAddr = ""  # blank value defaults to Service.Host value
Port = 4000
StartupMsg = "edgex-ui-go service started"
# MaxRequestSize limit the request body size in byte of put command
MaxRequestSize = 0 # value 0 unlimit the request size.
RequestTimeout = "5s"

[Clients]
    [Clients.core-data]
    Protocol = 'http'
    Host = 'edgex-core-data'
    Port = 59880

    [Clients.core-metadata]
    Protocol = 'http'
    Host = 'edgex-core-metadata'
    Port = 59881

    [Clients.core-command]
    Protocol = 'http'
    Host = 'edgex-core-command'
    Port = 59882

    [Clients.support-notifications]
    Protocol = 'http'
    Host = 'edgex-support-notifications'
    Port = 59860

    [Clients.support-scheduler]
    Protocol = 'http'
    Host = 'edgex-support-scheduler'
    Port = 59861

    [Clients.rules-engine]
    Protocol = 'http'
    Host = 'edgex-kuiper'
    Port = 59720

    [Clients.sys-mgmt-agent]
    Protocol = 'http'
    Host = 'edgex-sys-mgmt-agent'
    Port = 58890

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"
ConfigRegistryStem="edgex/appservices/"
ServiceVersion="2.0"

[APIGateway]
Server = "edgex-nginx"
ApplicationPort = 8000
ApplicationPortSSL = 8443
