name: edgex-ui
base: core22
type: app
grade: stable
confinement: strict
summary: EdgeX Graphical User Interface
description: Refer to https://snapcraft.io/edgex-ui
adopt-info: edgex-ui

epoch: 1

architectures:
  - build-on: arm64
  - build-on: amd64

apps:
  edgex-ui:
    command-chain:
      - bin/source-env-file.sh
    command: bin/edgex-ui-wrapper.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps: [go/1.18/stable]
    override-build: |
      cd $CRAFT_PART_SRC
      make build
      install -DT ./helper-go $CRAFT_PART_INSTALL/bin/helper-go
  
  web-static:
    plugin: dump
    source: cmd/edgex-ui-server
    prime: 
       - static/web/*
  
  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh
      edgex-ui-wrapper.sh: bin/edgex-ui-wrapper.sh

  edgex-ui:
    source: .
    plugin: make
    build-packages: 
      - git
    build-snaps:
      - go/1.18/stable
    stage-packages: [libzmq5]
    override-build: |
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi

      # set the version of the snap
      craftctl set version=$VERSION

      # write version to file for the build
      echo $VERSION > VERSION

      [ ! -d "vendor" ] && go mod download all || echo "skipping..."

      make build
      mkdir -p "$CRAFT_PART_INSTALL/bin"
      mkdir -p "$CRAFT_PART_INSTALL/config/edgex-ui-server/res"
      
      cp cmd/edgex-ui-server/edgex-ui-server $CRAFT_PART_INSTALL/bin/edgex-ui-server
      
      # change the StaticResourcesPath to point to $SNAP
      cat "./cmd/edgex-ui-server/res/configuration.toml" | \
        sed -e s@"StaticResourcesPath = \"./static\""@"StaticResourcesPath = \"\$SNAP/static\""@ > \
       "$CRAFT_PART_INSTALL/config/edgex-ui-server/res/configuration.toml"
       

