name: edgex-ui
base: core20 
type: app
adopt-info: metadata
grade: stable
confinement: strict

epoch: 1

architectures:
  - build-on: arm64
  - build-on: amd64

apps:
  edgex-ui:
    command: bin/edgex-ui-wrapper.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind

parts:
  web-static:
    plugin: dump
    source: cmd/edgex-ui-server
    prime: 
       - static/web/*
       
  local-snap-assets:
    plugin: dump
    source: snap/local/runtime-helpers
    prime:
      - bin/*

  edgex-ui:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    build-snaps:
      - go/1.17/stable
    stage-packages: [libzmq5]
    override-build: |
      go mod tidy

      # the version is needed for the build
      cat ./VERSION

      [ ! -d "vendor" ] && go mod download all || echo "skipping..."

      make build
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/config/edgex-ui-server/res"
      cp cmd/edgex-ui-server/edgex-ui-server $SNAPCRAFT_PART_INSTALL/bin/edgex-ui-server
      # change the StaticResourcesPath to point to $SNAP
      cat "./cmd/edgex-ui-server/res/configuration.toml" | \
        sed -e s@"StaticResourcesPath = \"./static\""@"StaticResourcesPath = \"\$SNAP/static\""@ > \
       "$SNAPCRAFT_PART_INSTALL/config/edgex-ui-server/res/configuration.toml"
       
  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png
      
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-ui.metainfo.xml]   

